services:
  vector:
    image: timberio/vector:0.39.0-alpine
    container_name: vector 
    volumes:
      - ./vector.toml:/etc/vector/vector.toml
      - /var/run/docker.sock:/var/run/docker.sock
    command: --config /etc/vector/vector.toml
    depends_on:
      - loki
    networks:
      - monitor_net
      - traefik_proxy
