apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: ingressroutetls
  namespace: whoami
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`whoami.enriqueav.com`)
      priority: 10
      services:
      - name: whoami
        port: 80
  tls:
    certResolver: myresolver
