apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: ingressroutetls
    #namespace: whoami
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`test.xxx.com`) && PathPrefix(`/tls`)
    kind: Rule
    services:
    - name: frontend
      port: 80
  tls:
    certResolver: myresolver
