services:
  plex:
    image: linuxserver/plex:latest
    restart: unless-stopped
    container_name: plex
    networks:
      - traefik_proxy
    ports:
      # Main Plex port
      - 32400:32400/tcp
      - 8324:8324/tcp
      - 32469:32469
      - 1900:1900/udp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
    # network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
      - VERSION=docker
      - ADVERTISE_IP=http://plex.${DOMINIO}/
      - PLEX_CLAIM=claim-ztpTQVbEmDquyzdQyxop
    env_file:
      - .env
    volumes:
      - ${DATA_DIRECTORY}/plex:/config
      - ${MEDIA}/downloads:/data/movies
    devices:
      - /dev/dri:/dev/dri
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.plex.rule=Host(`plex.${DOMINIO}`)"
      - "traefik.http.routers.plex.entrypoints=web,websecure"
      - "traefik.http.routers.plex.tls.certresolver=myresolver"
      - "traefik.http.services.plex.loadbalancer.server.port=32400"
