services:
  radarr:
    image: linuxserver/radarr:latest
    restart: unless-stopped
    container_name: radarr
    networks:
      - traefik_proxy
    volumes:
      - ${DATA_DIRECTORY}/radarr:/config
      - ${MEDIA}:/data
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
    labels:
      - traefik.enable=true
      - traefik.http.services.radarr.loadbalancer.server.port=7878
      - traefik.http.routers.radarr-auth.rule=Host(`radarr.${DOMINIO}`)
      - traefik.http.routers.radarr-auth.priority=1
      - traefik.http.routers.radarr-auth.entrypoints=websecure
      - traefik.http.routers.radarr-auth.tls.certresolver=myresolver
      - traefik.http.routers.radarr-auth.middlewares=authentik@docker
      - traefik.http.routers.radarr.rule=Host(`radarr.${DOMINIO}`) && PathPrefix(`/api`)
      - traefik.http.routers.radarr.priority=2
      - traefik.http.routers.radarr.entrypoints=websecure
      - traefik.http.routers.radarr.tls.certresolver=myresolver