#https://github.com/timothymiller/cloudflare-ddns
version: '3.9'
services:
  cloudflare-ddns:
    image: timothyjmiller/cloudflare-ddns:latest
    container_name: cloudflare-ddns
    network_mode: 'host'
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ${DATA_DIRECTORY}/cloudfare:/config.json
    restart: unless-stopped
