services:
  web:
    image: nginx
    expose:
      - "80"
    volumes:
      - ./web/html:/usr/share/nginx/html:ro
    networks:
      - traefik_proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.web.rule=Host(`web.${DOMINIO}`)"
      - "traefik.http.routers.web.entrypoints=websecure"
      - "traefik.http.routers.web.tls.certresolver=myresolver"
      - "traefik.http.services.web.loadbalancer.server.port=80"

    environment:
      - PUID=1000
      - PGID=1000

  app1:
    image: nginx
    expose:
      - "80"
    volumes:
      - ./app1/html:/usr/share/nginx/html:ro
    networks:
      - traefik_proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app1.rule=Host(`app1.${DOMINIO}`)"
      - "traefik.http.routers.app1.entrypoints=websecure"
      - "traefik.http.routers.app1.tls.certresolver=myresolver"
      - "traefik.http.services.app1.loadbalancer.server.port=80"
    environment:
      - PUID=1000
      - PGID=1000
