services:
  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    dns:
      - 127.0.0.1
      - 9.9.9.9
    environment:
      TZ: 'TZ=Europe/Madrid'
      WEBPASSWORD: ${PASSWORD}
      PIHOLE_DNS_: 9.9.9.9;149.112.112.112;1.1.1.1
      DNSSEC: 'true'
      ServerIP: 192.168.0.204 # Actual server IP. Matches DHCP conf file IP
      VIRTUAL_HOST: pihole.${DOMINIO} # Same as port traefik config
      DNSMASQ_LISTENING: all
      DHCP_ACTIVE: 'true'
      DHCP_START: 192.168.0.100
      DHCP_END: 192.168.0.199
      DHCP_ROUTER: 192.168.0.1
      DHCP_LEASETIME: 6
      WEBTHEME: default-dark
      PIHOLE_DOMAIN: lan
    volumes:
      - '${PIHOLE_DIRECTORY}/pihole:/etc/pihole/'
      - '${PIHOLE_DIRECTORY}/dnsmasq.d:/etc/dnsmasq.d/'
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
    networks:
      dhcp:
        ipv4_address: '172.31.0.100'
      traefik_proxy:
    depends_on:
      - dhcphelper
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pihole.rule=Host(`pihole.${DOMINIO}`)"
      - "traefik.http.services.pihole.loadbalancer.server.port=80"
      - "traefik.http.routers.pihole.entrypoints=web"

  dhcphelper:
    image: noamokman/dhcp-helper
    container_name: dhcp-helper
    restart: unless-stopped
    network_mode: "host"
    command: -s 172.31.0.100
    cap_add:
      - NET_ADMIN

networks:
  dhcp:
    ipam:
      config:
        - subnet: 172.31.0.0/16
