services:
  jackett:
    image: linuxserver/jackett:latest
    restart: unless-stopped
    container_name: jackett
    networks:
      - traefik_proxy
    volumes:
      - ${DATA_DIRECTORY}/jackett:/config/Jackett
      - ${MEDIA}/torrents:/torrents
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jackett.rule=Host(`jackett.${DOMINIO}`)"
      - "traefik.http.routers.jackett.entrypoints=websecure"
      - "traefik.http.routers.jackett.tls.certresolver=myresolver"
      - "traefik.http.services.jackett.loadbalancer.server.port=9117"
#      - "traefik.http.routers.jackett.middlewares=authentik@docker"
