services:
  homarr:
    image: ghcr.io/ajnart/homarr:latest
    restart: unless-stopped
    container_name: homarr
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${DATA_DIRECTORY}/homarr/configs:/app/data/configs
      - ${DATA_DIRECTORY}/homarr/icons:/app/public/icons
      - ${DATA_DIRECTORY}/homarr/data:/data
    environment:
      - PUID=1000
      - PGID=1000
      - BASE_URL=https://home.${DOMINIO}
    networks:
      - traefik_proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.homarr.rule=Host(`home.${DOMINIO}`)"
      - "traefik.http.routers.homarr.entrypoints=websecure"
      - "traefik.http.routers.homarr.tls.certresolver=myresolver"
      - "traefik.http.services.homarr.loadbalancer.server.port=7575"
      - traefik.http.routers.homarr.middlewares=authentik@docker
